# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-05 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
