# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-08 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20191208_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id'], 'verbose_name': '客户信息表', 'verbose_name_plural': '客户信息表'},
        ),
        migrations.AddField(
            model_name='customer',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
