# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-11 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20191211_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consult_now', to='app01.Customer', verbose_name='所咨询客户'),
        ),
    ]
