# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-19 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0010_auto_20191219_2056'),
        ('app01', '0010_auto_20191212_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(to='rbac.Role'),
        ),
    ]
